language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

env:
  global: 
  - PLUGIN_DIR: aiida-diff
  
  matrix:
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: tests
  - TEST_AIIDA_BACKEND: sqlalchemy
    TEST_TYPE: tests
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: docs
    READTHEDOCS: 'True'
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: pre-commit

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install cookiecutter
- cookiecutter --no-input .
- cd ${PLUGIN_DIR}
- pip install -e .[docs,pre-commit,testing]
- reentry scan

script:
- >
    if [ "$TEST_TYPE" == "docs" ] ; then 
        cd docs;
        make;
    elif [ "$TEST_TYPE" == "pre-commit" ] ; then 
        git init;
        git add -A;
        pre-commit install;
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 );
    else
        pytest -v;
    fi
