language: python
python:
- "2.7"
- "3.6"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.6"

env:
  global: 
  - PLUGIN_DIR: aiida-diff
  - TEST_AIIDA_BACKEND: django
  - AIIDA_DEVELOP_GIT_HASH: 7854680b268dcf29425a866256c9b34bdaa40ae5

  matrix:
  - AIIDA_VERSION: stable
    TEST_TYPE: tests
  - AIIDA_VERSION: stable
    TEST_TYPE: tests
    TEST_AIIDA_BACKEND: sqlalchemy
  - AIIDA_VERSION: stable
    TEST_TYPE: docs
    READTHEDOCS: 'True'
  - AIIDA_VERSION: stable
    TEST_TYPE: pre-commit

  - AIIDA_VERSION: develop
    TEST_TYPE: tests
  - AIIDA_VERSION: develop
    TEST_TYPE: tests
    TEST_AIIDA_BACKEND: sqlalchemy

matrix:
  exclude:
  # stable version doesn't work with python3
  - python: "3.6"
    env:
      AIIDA_VERSION: stable

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install cookiecutter yapf
- cookiecutter --no-input .
- pip install -e ${PLUGIN_DIR}[docs,pre-commit,testing]
- if [ "$AIIDA_VERSION" == "develop" ]; then .travis-data/install_aiida_github.sh ; fi  # installs develop branch
- reentry scan -r aiida
- cd ${PLUGIN_DIR}

script:
- >
    if [ "$TEST_TYPE" == "docs" ] ; then 
        cd docs;
        make;
    elif [ "$TEST_TYPE" == "pre-commit" ] ; then 
        git init;
        git add -A;
        pre-commit install;
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 );
    else
        pytest -v;
    fi
